[package]
name = "solana_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "2.2.1"
dialoguer = "0.11.0"
lazy_static = "1.5.0"
solana-client = "2.2.0"
solana-program = "2.2.1"
dotenv = "0.15"
